# Generated by Django 4.1.5 on 2023-01-31 14:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Spot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('location', models.CharField(max_length=200)),
                ('thumbnail', models.CharField(max_length=200)),
                ('color', models.CharField(blank=True, max_length=20)),
            ],
        ),
    ]
