# Generated by Django 4.1.5 on 2023-01-31 14:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('spot', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MyUser',
            fields=[
                ('uid', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('spots', models.ManyToManyField(related_name='follower', to='spot.spot')),
            ],
        ),
    ]
